package org.example.simplepayments

enum class ErrorCodes(val code: Int) {
    USER_NOT_FOUND(100),
    USER_ALREADY_EXISTS(101),
    USER_HAS_INSUFFICIENT_BALANCE(200),
    TRANSACTION_NOT_FOUND(300),
    PRODUCT_NOT_FOUND(400),
    PRODUCT_ALREADY_EXISTS(401),
    CATEGORY_ALREADY_EXISTS(501),
    CATEGORY_NOT_FOUND(500),
    COUNT_NOT_ENOUGH(600)
}